concourse-web:
  image: innitdocker/concourse-ci
  entrypoint: /concourse-web.sh
  environment:
    CONCOURSE_URL:
    CLIENT_ID:
    CLIENT_SECRET:
    ORG:
  volumes:
  - /var/lib/concourse/keys
  ports:
  - 8080:8080
  - 2222:2222

concourse-worker:
  image: innitdocker/concourse-ci
  entrypoint: /concourse-worker.sh
  privileged: true
  environment:
    CONTAINER_DELAY: 5 #seconds, wait for the TSA setup
  volumes_from:
  - concourse-web
  net: container:concourse-web
